version: "3.7"

services:

  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    hostname: myhost
    environment:
      POSTGRES_DB: Tarea1SD
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    
    volumes:
      - /Documentos/T1/postgres:/var/lib/postgresql/data
      - ./Postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      
    ports:
      - "9091:5432"
  node:
    image: ejemplo-node:latest
    container_name: node-server
    ports:
      - "3001:3000"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"