version: "3.9"

services:

  db:
    build: ./Postgres
    restart: always
    container_name: postgres
    ports:
      - "9091:5432"
    environment:
      POSTGRES_DB: Tarea1SD
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    
  redis:
    build: ./Redis
    container_name: redis
    ports:
      - "6379:6379"

  node:
    build:  ./Node
    container_name: node-server
    ports:
      - "3001:3000"