version: '3.7'

services:

  cliente:
    container_name: cliente
    build: ./Cliente
    depends_on:
      - redis
      - servidor
    ports:
      - "3000:3000"

  servidor:
    container_name: servidor
    build: ./Servidor
    depends_on:
      - db
    ports:
      - "8030:8030"

  db:
    image: docker.io/bitnami/postgresql:11
    container_name: postgres
    volumes:
      - ./Postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_DATABASE=Tarea1SD
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=admin
    ports:
      - "9091:5432"

    
  redis:
    container_name: redis
    image: redis:6.2.6
    restart: always
    ports:
      - "8031:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: ["redis-server","--bind","redis","--maxmemory 2mb","--maxmemory-policy allkeys-lru"]


